# type: number
# required: true
# description: コンフィグのVersion番号
version = 2

# type: string
# required: true
# description: エージェント名（ウィザードで入力したもの）
name = "agent-container"

# type: string
# required: false
# description: エージェント共通のプロンプト
instruction = """
You are a helpfull assistant.
"""

[setup]
# type: string(multiline)
# required: false
# description: エージェントbuild時に実行する
script = """
node install playwright
pip install playwright
"""

[[skills]]
# type: string("local" | "hosted")
# required: false
# description: スキルの参照元（local: CWD配下, hosted: Vercel Blob）
source="local"

# type: string
# required: source = "local" の場合 true
# description: ローカルスキルのディレクトリ
path="skills/pptx"

[[skills]]
source="local"
path="skills/xlsx"

[[skills]]
# type: string("local" | "hosted")
# required: false
# description: スキルの参照元（local: CWD配下, hosted: Vercel Blob）
source="hosted"

# type: string
# required: source = "hosted" の場合 true
# description: Hosted skill の slug
slug="generated-pptx-skill"


[[files]]
# type: string
# required: false
# description: ファイルのディレクトリ
path="files/knowledge.md"

[[files]]
path="files/react-best-practice.md"
